### ISSUE TITLE
是否可以切换 Markdown 到 GFM?

### ISSUE THREAD

**Issue by jiyinyiyong** [jimmykuu/gopher#19]
主要还是处理换行的问题吧, 论坛回复经常出现文本块, 不便阅读, 也不便书写了
Github 版本的 Markdown 对原来的 Markdown 做了改进, 很多细节更舒服一些.
包括代码块的语法也有改进 https://help.github.com/articles/github-flavored-markdown
JS 方面的模块实现主要是 Marked https://github.com/chjj/marked#usage
通过 `{gfm: true, breaks: true}` 可以开启 GFM 支持.
GFM 在其他若干个中文编程社区已经长期使用, 因此我认为适合 Go 社区支持 GFM.

**Comment by jimmykuu** [comment]
已经改用 editor.md 编辑器，默认支持 GFM 。
