### ISSUE TITLE
https的页面不能引入http的资源.

### ISSUE THREAD

**Issue by ggaaooppeenngg** [jimmykuu/gopher#48]
目前没有解决页面中包含很多七牛的http的资源.
在浏览器console.log 里面会有这样的输出:

GET https://gopher.qiniudn.com/static/css/bootstrap.min.css?v=3.3.0 net::ERR_INSECURE_RESPONSE

好像是七牛的https的域名不一样需要修改.

**Comment by meteormatt** [comment]
这个`gopher.qiniudn.com`不支持HTTPS

**Comment by jimmykuu** [comment]
已通过自建图片服务器解决了
