### ISSUE TITLE
安装后出错？

### ISSUE THREAD

**Issue by shaohao2014** [jimmykuu/gopher#50]
1、安装：go get github.com/jimmykuu/gopher/server
2、运行：go run d:\go\src\crypto\tls\generate_cert.go --host 127.0.0.1：8888
3、出错：GetFileAttributesEx d:\go\src\crypto\tls\generate_cent.go
之后：
1、我在cmd里边设置代理：（我用的是xp系统）
set http_proxy=127.0.0.1：8087（我用的是GoAgent）
2、重新运行安装流程，结果：错误依旧。
3、我查看了 d:\go\src 目录，里边并没有 crypto 目录 。这是怎么回事？
求解？谢谢！

**Comment by jimmykuu** [comment]
刚合并的分支，还有部分问题，通过一下方式可以先运行起来，先不用https的方式运行

    go get github.com/jimmykuu/gopher

然后编译 github.com/jimmykuu/gopher/server，主要 etc, static, templates三个目录要在当前目录下，运行编译后的server可以启动，当然要先启动mongodb
