### ISSUE TITLE
新功能加入

### ISSUE THREAD

**Issue by Follen** [jimmykuu/gopher#57]
注册验证邮箱，取消收藏，删除用户，消息提醒系统

**Comment by jimmykuu** [comment]
验证注册邮箱是特地取消掉的，刚开始也是用的验证，但是问题比较多，比如收不到邮件，被认为是垃圾邮件等。

取消收藏确实需要增加，收藏功能也要弄一下，这块我会尽快重构下。

消息提醒功能有个小伙伴贡献过代码，但是还不是很完美，功能就没有放出来。

删除用户目前还没提供，这块我还需要仔细考虑下。

**Comment by jimmykuu** [comment]
2.0 版本重构中，这些功能能尽量考虑进去。
