### ISSUE TITLE
注册用户验证码不显示

### ISSUE THREAD

**Issue by marknewmail** [jimmykuu/gopher#61]
注册用户验证码不显示

**Comment by jimmykuu** [comment]
方便截个图发我邮箱不？jimmy.kuu@gmail.com

**Comment by marknewmail** [comment]
sent

**Comment by gobet8** [comment]
因为你没有填写,key

配置文件必须要写啊
{
	"host": "http://localhost:8888",
	"port": 8888,
	"db":"localhost:27017",
	"cookie_secret": "05e0ba2eca9411e18155109add4b8aac",
	"smtp_username": "username@example.com",
	"smtp_password": "password",
	"smtp_host": "smtp.example.com",
	"smtp_addr": "smtp.example.com:25",
	"from_email": "who@example.com",
//把你自己的用户名填到这里,就是超管
	"superusers": "jimmykuu,another",
//没闹明白呢	
"analytics_file": "",
//七牛的KEY
	"qiniu_access_key": "",
	"qiniu_secret_key": "",
	"time_zone_offset": 8,
	"static_file_version": 1,
	"packages_download_path": "/tmp",
//这个也没找到	
"public_salt": "nXweu8Jq44FgEfgM1Pv4xH51",
	"github_auth_client_id": "3e2f7d7378289e2c9cc4",
	"github_auth_client_secret": "5b8de98c93711c3b837498faf9bccdacb8f272c0",
	"github_login_redirect": "/",
	"github_login_success_redirect": "/auth/signup",
	"cookie_secure": false,
//这个也不知道是什么
	"deferpanic_api_key": "",
//geetest 验证码 key需要去geetest 官网申请
    "gt_captcha_id": "geetest captcha id", 
    "gt_private_key": "geetest private key"
}

**Comment by joeleonjr** [comment]
Hi! I'm a security researcher @TruffleSecurity. I found a valid API key leaked in a comment in this Issue. I highly recommend rotating the API key immediately (not just deleting the comment). Here's a blog post I wrote on remediating these types of vulnerabilities: https://trufflesecurity.com/blog/remediate-leaked-api-keys-with-key-rotation.<br><br>If you can't find the leaked API key, you can use the following [TruffleHog](https://github.com/trufflesecurity/trufflehog) command to automatically scan for it:<br>`trufflehog github --repo https://github.com/<your_username>/<your_reponame> --issue-comments --only-verified`<br><br>If it's not clear where/what the security issue is, please let me know. I'd be happy to help. Please note that the API key might be in the past edit of a comment.<br><br><br><br>(cc @gie777)
