### ISSUE TITLE
测试以后简单bug提交,

### ISSUE THREAD

**Issue by agpaly** [jimmykuu/gopher#62]
一样一样说吧,
1,七牛云上传的失败
原因:作者填写的是七牛自己分配的url 这个得改,要么,头像组上传失败,
建议:写在readme里面,虽然不用写成配置文件
2.第三方包数据提交东西不做审核,如果弄垃圾广告就恶心了,
3.新建文章分类模板错误
<<<<<<< HEAD <<<<<<< HEAD 
新建文章分类

名称
  ======= ======= >>>>>>> 评论at 
新建文章分类

名称
  <<<<<<< HEAD >>>>>>> account 改成指针handler ======= >>>>>>> 评论at 
.....................................分割线..............
现在更改作者的代码,想做个简单的文章系统还是挺简单的,给作者点个赞最好加上用户权限,要么以后是个问题.....删号还得进数据库...

**Comment by gobet8** [comment]
deferpanic_api_key: deferpanic.com的Api Key，用于监控panic
这个是什么啊,deferpanic.com 打不开熬,

**Comment by jimmykuu** [comment]
1. 由于域名没备案，七牛 https 无法使用，正在着手自己搭建图片服务器；
2. 网站2.0版本正在重构 这块可能会去掉；
3. 模块已经更改，2.0版本重构中。
deferpanic 已经去掉
