### ISSUE TITLE
大大，你的golangtc.com上来了垃圾攻击了。。。

### ISSUE THREAD

**Issue by Schr0dingerCat** [jimmykuu/gopher#78]
不知道如何告诉你，就想了这个办法，
各种广告，需要大大费心处理下了

**Comment by jimmykuu** [comment]
针对此情况，增加了发布主题需要验证码，目前可以防掉机器发帖。增加了批量删除一个用户的所有主题功能。

再加个一定时间内限制发帖数量就可以防掉手工频繁发帖了。

**Comment by jimmykuu** [comment]
已增加半小时时间限制发帖。
