### ISSUE TITLE
论坛升级后发表帖子页面一片空白

### ISSUE THREAD

**Issue by fising** [jimmykuu/gopher#85]
https://golangtc.com/topic/new

回复框也看不到。不知道是因为账号问题，还是论坛系统存在bug？

论坛不支持站内消息，只能来这里了。抱歉。

**Comment by jimmykuu** [comment]
可以打开浏览器开发者工具看看什么错误。
另外可否告知你的操作系统和浏览器版本。

**Comment by fising** [comment]
我刚才重试了一次，已经正常了。

操作系统：macOS
浏览器：Google Chrome 72.0.3626.119（正式版本） （64 位）
